general:
  exp_name: 0208_B
  logdir: logs
  demodir: demos
  seed: 12
  sync: False

hardware:
  gpu: [0,1,2] 
  cpu_min: [1,9,17]
  cpu_max: [8,16,24]

environment:
  name: rlbench
  task: 
    name: stack_blocks
    params: 
      - 1
      - 0
      - 1
  headless: True
  camera: False
  obs_dim: auto
  act_dim: auto
  reward:
    reward_shaping_use: False
    reward_shaping_type: mse

agent:
  type: sac
  action_space: pick_and_place_3d
  gamma: 0.9 
  polyak: 0.995
  lr: 0.001
  alpha: 0.2
  hidden_sizes: [32,32]
  boundary_min: [0.1,-0.3,0.76,0.1,-0.3,0.76]
  boundary_max: [0.35,0.3,0.86,0.35,0.3,0.86]

buffer:
  replay_buffer_size: 5000

demo:
    demo_use: True  
    demo_buffer_size: 500
    demo_ratio: 0.1   
    demo_create: True
    demo_name: demo_0207_B

sampler:
  env_num: 6
  start_steps: 200
  max_ep_len: 5

trainer:
  steps_per_epoch: 2000
  epochs: 10
  batch_size: 128
  update_after: 1000
  update_every: 100
  update_factor: 10

tester:
  num_test_episodes: 20

logger:
  num_log_loss_points: 500
