general:
  exp_name: test01
  logdir: logs
  demodir: demos
  seed: 12
  sync: False

hardware:
  gpu: 0 
  cpu_min: 1
  cpu_max: 9

environment:
  name: simsim
  task: reach_target_no_distractors
  headless: True
  camera: False
  obs_dim: 3
  act_dim: 3
  reward:
    reward_shaping_use: False
    reward_shaping_type: mse

agent:
  type: sac
  action_space: xyz
  gamma: 0.9 
  polyak: 0.995
  lr: 0.001
  alpha: 0.2
  hidden_sizes: [32,32]
  boundary_min: [0.1,-0.2,0.76]
  boundary_max: [0.35,0.2,0.96]

buffer:
  replay_buffer_size: 5000

demo:
    demo_use: False  
    demo_buffer_size: 5
    demo_ratio: 0.1   
    demo_create: False
    demo_name: Restructure_01

sampler:
  env_num: 3
  start_steps: 200
  max_ep_len: 5

trainer:
  steps_per_epoch: 2000
  epochs: 10
  batch_size: 128
  update_after: 500
  update_every: 100
  update_factor: 1

tester:
  num_test_episodes: 20

logger:
  num_log_loss_points: 100
