mazes:
  square_7x7_base:
    maze_map: [[1, 1, 1, 1, 1, 1, 1],
            [1, 'r', 'r', 0, 'g', 'g', 1],
            [1, 'r', 'r', 0, 'g', 'g', 1],
            [1, 'r', 'r', 0, 'g', 'g', 1],
            [1, 'r', 'r', 0, 'g', 'g', 1],
            [1, 'r', 'r', 0, 'g', 'g', 1],
            [1, 1, 1, 1, 1, 1, 1]]
  square_7x7_wall:
    maze_map: [[1, 1, 1, 1, 1, 1, 1],
            [1, 'r', 'r', 0, 'g', 'g', 1],
            [1, 'r', 'r', 1, 'g', 'g', 1],
            [1, 'r', 'r', 1, 'g', 'g', 1],
            [1, 'r', 'r', 1, 'g', 'g', 1],
            [1, 'r', 'r', 0, 'g', 'g', 1],
            [1, 1, 1, 1, 1, 1, 1]]
  square_7x7_S:
    maze_map: [[1, 1, 1, 1, 1, 1, 1],
            [1, 'r', 1, 0, 0, 'g', 1],
            [1, 'r', 1, 0, 1, 'g', 1],
            [1, 'r', 1, 0, 1, 'g', 1],
            [1, 'r', 1, 0, 1, 'g', 1],
            [1, 'r', 0, 0, 1, 'g', 1],
            [1, 1, 1, 1, 1, 1, 1]]

ise_inits:
  sqaure_7x7_v1:
    r: [[1,1],[1,2],[2,1],[2,2],[3,1],[3,2],[4,1],[4,2],[5,1],[5,2]]
    g: [[1,4],[1,5],[2,4],[2,5],[3,4],[3,5],[4,4],[4,5],[5,4],[5,5]]
  sqaure_7x7_S_v1:
    r: [[5,1],[4,1],[3,1],[2,1],[1,1]]
    g: [[5,5],[4,5],[3,5],[2,5],[1,5]]