agent:
  action_space: pick_and_place_2d
  alpha: 0.2
  boundary_max:
  - 0.35
  - 0.3
  - 0.35
  - 0.3
  boundary_min:
  - 0.1
  - -0.3
  - 0.1
  - -0.3
  gamma: 0.9
  hidden_sizes:
  - 32
  - 32
  lr: 0.001
  polyak: 0.995
  type: sac
buffer:
  replay_buffer_size: 5000
demo:
  demo_buffer_size: 500
  demo_create: false
  demo_name: demo_B30_500
  demo_ratio: 0.1
  demo_use: true
environment:
  act_dim: 4
  camera: false
  headless: true
  name: rlbench
  obs_dim: 4
  reward:
    reward_shaping_type: mse
    reward_shaping_use: false
  task: stack_blocks
general:
  demodir: demos
  exp_name: B30_rlbench_truedemo
  logdir: logs
  seed: 12
  sync: false
hardware:
  cpu_max: 16
  cpu_min: 1
  gpu: 0
logger:
  num_log_loss_points: 500
sampler:
  env_num: 6
  max_ep_len: 5
  start_steps: 200
tester:
  num_test_episodes: 20
trainer:
  batch_size: 128
  epochs: 10
  steps_per_epoch: 2000
  update_after: 1000
  update_every: 100
  update_factor: 1
