process_0: 
  general:
    seednum: 1 
  agent: 
    type: ['sac'] # ['sac','td3','ddpg']
    sac:
      alpha: [0.1]
    gamma: [0.95]
    learning_rate: [0.001]
  environment:
    reward:
      reward_shaping_type: ['sparse'] # sparse / state_change_bonus
      reward_bonus: [0.0] #--- only if reward_shaping_type == state_change_bonus
  buffer:
    replay_buffer_size: [1e6]
    her:
      goal_selection_strategy: ['noher','final'] # final  ######################## HER ################
    hier:
      buffer_size: [1e6]
      lambda: # threshold
        mode: ['nohier','predefined']    ######################## HiER ################
        fix:
          lambda: [-20] # gympanda: -20
        predefined: 
          lambda_start: [-100] # gympanda: -50; gym: -100
          lambda_end: [-10] # gympanda: -10; gym: -10
      xi: # hier batch ratio 
        mode: ['fix'] # fix 
        xi: [0.5]     
    per:
      mode: ['noper'] # proportional               ######################## PER ################
  trainer:
    total_timesteps: [5e2]
  eval:
    freq: [5e1]
    num_episodes: [10]
  # structure is differend than in the config file #################################
  task:
    gym: ['PointMaze_UMaze-v3'] 
    #gympanda: ['PandaPush-v3']
  ise: 
    type: ['predefined_disc']
    # type: ['max','min',
    #              'predefined','predefined2stage','predefined3stage',
    #              'selfpaced','control', 'controladaptive'] ######################## E2H-ISE  ################## 
    range_growth_mode: ['simple'] 
####################################################################################


