general:
  exp_name: 0822_X
  logdir: logs
  demodir: demos
  seed: 0

hardware:
  gpu: [0,1,2] 
  cpu_min: [1,1,1]
  cpu_max: [32,32,32]

environment:
  name: input
  task: 
    name: input
    params: []
  headless: True
  obs_dim: auto
  act_dim: auto
  camera: False
  reward:
    reward_scalor: 1
    reward_bonus: 0.1
    reward_shaping_type: sparse

agent:
  type: input
  hidden_sizes: [256,256,256]
  boundary_min: auto
  boundary_max: auto
  gamma: 0.95 
  sac:
    polyak: 0.995
    lr: 0.001
    alpha: 0.2
  td3:
    target_noise: 0.2
    noise_clip: 0.5
    pi_lr : 0.001 
    q_lr : 0.001
    policy_delay : 2
    polyak : 0.995
    act_noise: 0.1

buffer:
  replay_buffer_size: 1e6
  her:
    goal_selection_strategy: input
    n_sampled_goal: 4

sampler:
  start_steps: 1e4
  max_ep_len: auto

trainer:
  total_timesteps: 5e5
  batch_size: 256
  update_after: 1e2
  update_every: 50

eval:
  freq: 5e3
  num_episodes: 20
  

logger:
  rollout:
    stats_window_size: 100
  train:
    stats_window_size: 1
  model:
    save:
      mode: pi
      best_start_t: 0.3
      freq: 5
