general:
  exp_name: 0928_X
  logdir: logs
  demodir: demos
  seed: random
  init_weights:
    bool: True
    mode: all # all / pi
    path: logs/0928_X_PandaPush-v3_sac_controldiscrete_const/0/model_backup/model_best_model

hardware:
  gpu: [0,1,2,3] 
  cpu_min: [1,1,1,1]
  cpu_max: [32,32,32,32]

environment:
  name: input # gympanda
  task: 
    name: input # PandaReach-v3 / PandaPush-v3 / PandaSlide-v3 (and dense versions)
    params: []
  headless: True
  obs_dim: auto
  act_dim: auto
  camera: False
  reward:
    reward_scalor: 1
    reward_bonus: 0.1
    reward_shaping_type: sparse # sparse / state_change_bonus

agent:
  type: input
  hidden_sizes: [256,256,256]
  boundary_min: auto
  boundary_max: auto
  gamma: 0.95
  polyak: 0.995
  learning_rate: 0.001
  sac:
    alpha: 0.2 # spinningup do not have "auto" option
  td3:
    target_noise: 0.2
    noise_clip: 0.5
    policy_delay : 2
    act_noise: 0.1

buffer:
  replay_buffer_size: input
  her:
    goal_selection_strategy: input # in SB3 only the orginal ones are implemented
    n_sampled_goal: 4
    state_check: true

sampler:
  start_steps: 10000 # in SB3 we cannot set it
  max_ep_len: auto

trainer:
  mode: input
  total_timesteps: 5e5
  batch_size: 256
  update_after: 1e2
  update_every: 50
  cl:
    type: input # predefined / selfpaced / selfpaceddual / controldiscrete / examplebyexample
    range_growth_mode: input # simple / discard / balancediscard
    ratio_discard_lag: 0.1 # Only if 'range_growth_mode' is 'discard' or 'balancediscard'
    balancediscard_ratio: 0.8  # Only if 'range_growth_mode' is 'balancediscard'
    predefined:
      pacing_profile: input  # linear / sqrt / quad
      pacing_sat: 0.8 
    selfpaced:
      conv_cond: 0.8
      window_size: 20
      step: 0.05
    selfpaceddual:
      upper_cond: 0.8
      lower_cond: 0.2
      window_size: 20
      step: 0.05
    controldiscrete:
      target_profile: input # const / linear / sqrt / quad
      target_sat: 0.8 
      target_sat_value: 0.8
      step: 0.01
      window_size: 20
      const_sin:
        amp: 0.05
        freq_divide: 50
    examplebyexample:
      conv_cond: 0.8
      window_size: 20
    # controlpd:
    #   target_profile: linear
    #   target_sat: 0.75
    #   p: 0.01
    #   d: 0

eval:
  freq: 1e4
  num_episodes: 20
  

logger:
  rollout:
    stats_window_size: 10
  train:
    stats_window_size: 1
  state_change:
    stats_window_size: 100
  model:
    save:
      mode: pi
      best_start_t: 0.0
      freq: 20